### ISSUE TITLE
Replace all fail 

### ISSUE THREAD

**Issue by renatovilasboas** [FagnerMartinsBrack/str-replace#5]
Hi, 

I used the text : ' value value ' and try to replace to text ' 1 ', the result is ' 1 value ', just the first item was replaced.

I use the version : "str_replace": "^0.1.6",

**Comment by FagnerMartinsBrack** [comment]
@renatovilasboas Did you try `replace.all("value").from("value value ").with("1")`? If that doesn't work feel free to create a Pull Request with a failing test.

**Comment by renatovilasboas** [comment]
It works! I understand,  the str_replace is a old version in npm, you create a new str-replace package and this really works.
